config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions

  root 'home#index'

  get '/about' => 'home#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ActiveRecord::Base
    include HasGravatar
    belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/has_gravatar.rb
module HasGravatar

    def gravatar
        "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
    end

end

app/models/question.rb
class Question < ActiveRecord::Base
    include HasGravatar

    has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

    def create
        question = Question.find(params[:answer][:question_id])
        answer = question.answers.create(answer_params)

        MainMailer.notify_question_author(answer).deliver_later

        session[:current_user_email] = answer_params[:email]
        redirect_to question
    end

    private def answer_params
        params.require(:answer).permit(:email, :body)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc).all
  end

  def about
  end

  def temp
    redirect_to root_path 
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

    def show
        @question = Question.find(params[:id])
        @answers = @question.answers.order(created_at: :desc)
    end

    def create
        Question.create(question_params)
        session[:current_user_email] = question_params[:email]
        redirect_to root_path
    end

    private def question_params
        params.require(:question).permit(:email, :body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

 def current_user_email
    session[:current_user_email]
 end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_navbar.erb
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<a class="navbar-brand" href="#">Just a Rails Test</a>
		</div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><div class="navbar-text"><%= current_user_email %></div>
                <li>
                    <button type="button" class="btn btn-success navbar-btn btn-sm" data-toggle="modal"
                        data-target="#new-question-modal">Ask A Question</button>
                </li>
            </ul>
        </div>
	</div><!-- /.container-fluid -->
</nav>

app/views/home/_new_answer_form.erb
<div id="new-answer-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Give your answer</h4>
      </div>
      <%= form_for :answer, url: '/answers', html: { class: 'form-horizontal' } do %>
          <input type="hidden" name="answer[question_id]" value="<%= @question.id %>">
          <div class="modal-body">
              <div class="form-group">
                <label class="control-label col-sm-2" for="email">Email:</label>
                <div class="col-sm-10">
                  <input type="email" class="form-control" id="email" name="answer[email]"
                    value="<%= current_user_email %>" placeholder="enter email"
                    required>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2" for="answer">Answer:</label>
                <div class="col-sm-10">
                  <textarea type="text" class="form-control" id="answer" name="answer[body]" placeholder="What's your answer?" required /></textarea>
                </div>
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/home/_new_question_form.erb
<div id="new-question-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
	<div class="modal-content">
	  <div class="modal-header">
		<h4 class="modal-title">Ask Your question</h4>
	  </div>
      <%= form_for :question, url: '/questions', html: { class: 'form-horizontal' } do %>
		  <div class="modal-body">
			  <div class="form-group">
				<label class="control-label col-sm-2" for="email">Email:</label>
				<div class="col-sm-10">
				  <input type="email" class="form-control" id="email" name="question[email]"
                     placeholder="Enter email" value="<%= current_user_email %>" required>
				</div>
			  </div>
			  <div class="form-group">
				<label class="control-label col-sm-2" for="question">Question:</label>
				<div class="col-sm-10"> 
				  <textarea type="text" class="form-control" id="question" name="question[body]" placeholder="What's your question?" required /></textarea>
				</div>
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			<button type="submit" class="btn btn-primary">Submit</button>
		  </div>
		</div>
	<% end %>
  </div>
</div>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<div class="well"> <h1>Q&A Site</h1></div>

<div class="container">
    <div class="boxes">
        <% @questions.each do |q| %>
        <div class="media" data-target="<%= question_path(q) %>">
            <div class="media-left">
                <a href="#">
                    <img class="media-object" src="<%= q.gravatar %>">
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading"><%= q.email %> asked:</h4>
                <div class="time hidden-xs"><%= time_ago_in_words q.created_at %> ago</div>
                <div><%= truncate q.body, length: 300 %></div>
                <div class="answer-button hidden-xs">
                    <a href="<%= question_path(q) %>" class="btn btn-success button-xs">View Answers</a>
                </div>
            </div>
        </div>
        <% end %>
        <% if @questions.empty? %>
            <div class="alert alert-info">No Questions.</div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTest</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'home/navbar' %>
	<%= yield %>
    <%= render 'home/new_question_form' %>
  </body>

</html>

app/views/questions/show.html.erb
<div class="container">
    <div class="lead">
        <div class="media">
            <div class="media-left">
                <a href="#">
                    <img class="media-object" src="<%= @question.gravatar %>">
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading"><%= @question.email %> asked:</h4>
                <%= @question.body %>
            </div>
        </div>
        <div>
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal"
                data-target="#new-answer-modal">Submit new answer</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <%= render 'home/new_answer_form' %>
            <% @answers.each do |answer| %>
                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object" src="<%= answer.gravatar %>">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading"><%= answer.email %> answered:</h4>
                       <div><%= time_ago_in_words answer.created_at %> ago</div>
                        <%= answer.body %>
                    </div>
                </div>
            <% end %>
			<% if @answers.empty? %>
				<div class="alert alert-info">No Answers.</div>
			<% end %>
        </div>
    </div>
</div>